### ISSUE TITLE
Edge Loss on Tracklets

### ISSUE THREAD

**Issue by hcagri** [dvl-tum/SUSHI#3]
Hi,

Thanks for sharing the code, amazing work. I would like to ask something because as I read the paper again and again it is still unclear to me. For the edges that connect tracklets, how do you compute the loss. Because the binary labeling while connecting detections is very intuitive, but the tracklets formed in the lower levels of the hierarchy may not contain detections belonging to the same individual. So in that case, what is the true label for the edges connecting the tracklets? 

Thanks.

**Comment by ocetintas** [comment]
Hi, 
Thanks for the kind words. We simply denote a cluster as identity x provided that identity x makes up more than 50% of the detections of that cluster. Otherwise, the cluster is labeled as unknown. This is controlled by the parameter node_id_min_ratio set to 0.5. But in practice, changing this parameter does not influence the tracking performance much because lower levels perform quite well and such cases are uncommon.
